Update readme and documentation
TUV-SUD-Product-Service-GmbH/QuteStyle pull request #31
Opened 2022-05-17 06:46 UTC by Marinnia

2022-05-17 10:33 UTC, p5k369 commented
Hey @Marinnia, thank you for your pull request.  Would you please run `pre-commit run -a` prior to your next commit, that should solve all minor issues.

2022-07-18 07:38 UTC, p5k369 requested changes

2022-07-18 07:38 UTC, p5k369 commented on README.md
> +We defined [custom widgets](./docs/widgets.md#widgets), such that they fit to the overall style and implemented new behaviour. A selection can be found in the Test-App:
```suggestion
We defined [custom widgets](./docs/widgets.md), such that they fit to the overall style and implemented new behaviour. A selection can be found in the Test-App:
```

2022-07-18 07:38 UTC, p5k369 commented on docs/qs_main_window.md
> +# Main Window
Is this a placeholder for information about how to use the main window?

2022-07-18 07:38 UTC, p5k369 commented on docs/widgets.md
> +The DropLabel offers a convenient way to display the could icon with an associated text and for example
```suggestion
The DropLabel offers a convenient way to display the cloud icon with an associated text and for example
```

2022-07-18 09:23 UTC, p5k369 approved these changes
Thank you for documenting.

2022-07-19 08:52 UTC, Daigon2 approved these changes

2022-07-19 08:53 UTC, merged